# Generated by Django 4.1 on 2022-09-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='پیوند یکتا')),
                ('bio', models.TextField(blank=True, help_text='توضیحات فردی', null=True, verbose_name='درباره ی من')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, help_text='11 رقم وارد کنید', max_length=11, null=True, verbose_name='شماره همرا')),
                ('age', models.CharField(blank=True, help_text='2رقم وارد کنید', max_length=2, null=True, verbose_name='سن')),
                ('job', models.CharField(blank=True, max_length=50, verbose_name='سمت شغلی')),
                ('gender', models.CharField(blank=True, choices=[('m', 'آقا'), ('f', 'خانم')], max_length=1, null=True, verbose_name='جنسیت')),
                ('nc', models.CharField(blank=True, max_length=11, null=True, verbose_name='کدملی')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
