# Generated by Django 4.1 on 2022-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Dessert', 'پیش غذا'), ('Main Meal', 'غذای اصلی'), ('Drink', 'نوشیدنی')], max_length=15),
        ),
    ]
